version: "3.9"

services:
  valhalla:
    image: ghcr.io/solithcy/valhalla_safety:safety
    container_name: valhalla-safe
    restart: unless-stopped
    volumes:
      - ./custom_files:/custom_files
    command: ["valhalla_service", "/custom_files/valhalla.json"]
    working_dir: /valhalla

  streetsafe-server:
    build:
      context: https://github.com/cb671/streetsafe-server.git#${BUILD_BRANCH:-main}
    container_name: streetsafe-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=3000
    expose:
      - "3000"

  streetsafe-client:
    build:
      context: https://github.com/cb671/streetsafe-client.git#${BUILD_BRANCH:-main}
    container_name: streetsafe-client
    restart: unless-stopped
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: streetsafe-nginx
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - streetsafe-server
      - streetsafe-client
      - valhalla
